### ISSUE TITLE
Saving templates on iOS 

### ISSUE THREAD

**Issue by JohnSparham** [FBarrca/obsidian-handwritten-notes#20]
The template file is not accessible on iOS,  or i dont know were to find the dot files lol.   If an option to the file option menu to create template could be added is would be very handy!  Thanks

**Comment by FBarrca** [comment]
The option to access the folder from Obsidian is only available on the desktop due to API limitations. From iPadOS you should use the Files app. The path given(.obsidian/plugins/handwritten-notes/templates/) starts from the main folder of your vault, so you should search from there. It might not be shown by default, if that is the case, enable view hidden files in the explorer settings.
