### ISSUE TITLE
Link to other Obsidian notes missing

### ISSUE THREAD

**Issue by 5puKn2rKULnv** [FBarrca/obsidian-handwritten-notes#4]
I love the plugin, but this is the one thing that I am still missing. I can't add links that connect to other obsidian notes.

**Comment by FBarrca** [comment]
I'll look into it, It's something I have had in my mind, but can't think of a good way to do so. 
If you think of a good way to do so, please PR or share it on this thread.

**Comment by kraibse** [comment]
@mdelgadoschwar Well, for now, you'd need to copy the Obsidian URL from the Obsidian file tree manually.

**Comment by mdelgadoschwar** [comment]
@kraibse what do you mean? I have tried copying the Obsidian URL of the pdf, but if I insert it to any file outside of Obsidian, I cannot use it as a link. 

@FBarrca the most ideal situation of course would be that if I write double brackets into the pdf file, Obsidian activates and I can choose my link. 
However if that doesn't work, an alternative would be to work on two layers: The first layer is already done, the drawing layer, which happens with the pdf annotation software. The second layer is within Obsidian, where I can add notes to the pdf. Within these notes I can then add my comments + links. (The comments are also important, because they help with the search function in Obsidian.) 

That is as far as my ideas went.

**Comment by kraibse** [comment]
@mdelgadoschwar
Try pasting the Obsidian URL into your browser. If the installer worked its magic the specified note will open. You'll then just have to insert a clickable link with or without alternate text. Your system should recognize the URL.

As per the second part there is a PDF annotator plugin that works pretty well with text highlighting and bookmarks. All within Obsidian and markdown based if you wanted to edit later.

**Comment by mdelgadoschwar** [comment]
@kraibse Thanks for the advice. Using the Obsidian URL in my web browser does indeed work! And I can do the same thing within my pdf annotator, when making a link there, and telling it that it is a web link. 

It would be amazing if I could directly write double brackets in the pdf annotator, and then a search box from Obsidian would appear with which I could select my link. Right now I have to first copy the title of the note, paste it in the pdf, go back to the note, copy its URL, and then go back to the pdf to create the web-link in the pdf. Unless I am working on two screens this is going to be very annoying. 
And I am guessing that Obsidian doesn't know I am making these links, meaning the pdf is not seen in the list of backlinks in other files. 

Also, while this sort of solves the linking issue, it does not solve the issue that Obsidian can only read the title of the pdf and not any of the text I may have written there. I am guessing that this will have a negative impact on how easy it is to find the file later. 

I have not yet tried the PDF annotator plugin next to this one, but it also seems cumbersome. It requires then to have two files, the pdf (which really, I am only using to make my drawings or write my equations), and then a second markdown file. Worse even, if I change the name of the pdf, the link between the markdown and pdf is lost.

**Comment by kraibse** [comment]
@mdelgadoschwar Someone would have to modify the Obsidian pdf editor. I was thinking of attempting another stylus solution that works within notes and even canvases. Still I have not started this project.

Also, using the backlink style in the pdf editor will not work since its an external app.

**Comment by mdelgadoschwar** [comment]
Oh my goodness, 

I have just found the Obsidian hotkey "Handwritten Notes: Create and embed from favorite template". This allows me to have my main note, and attach to it the pdf drawings (that I can even edit afterwards!!!). 
This is perfect. Took me this long to find that option, but that is the key to making this workable. 

Maybe add this in your description. Because now I can actually link my one note with other notes, find them in the graph view, and still work with my drawings and equations. 

Thanks a lot for your effort guys! What a contribution!

**Comment by kraibse** [comment]
You might be also interested in the pdf embed for specific pages.

Just embed a pdf as usual and add a page number to it. `![[my-notes.pdf#page=8]]`
